<?php

namespace Database\Seeders;

use App\Enums\ProductType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class StoreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('stores')->insert([
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::GROCERY->value,
                'tax' => 5,
                'tax_number' => 'VAT123457',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 7.00,
                'name' => 'Fresh Grocer',
                'slug' => Str::slug('Fresh Grocer'),
                'phone' => '1234567891',
                'email' => 'freshgrocer@example.com',
                'logo' => '10',
                'banner' => '11',
                'address' => '456 Green Lane, City',
                'is_featured' => true,
                'opening_time' => '07:00:00',
                'closing_time' => '21:00:00',
                'delivery_charge' => 3.00,
                'delivery_time' => '30-45 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 30,
                'veg_status' => 1,
                'off_day' => 'Wednesday',
                'enable_saling' => 1,
                'meta_title' => 'Fresh Grocer - Your Neighborhood Grocery Store',
                'meta_description' => 'Find fresh and organic grocery items at Fresh Grocer.',
                'meta_image' => 'fresh_grocer_meta_image.png',
                'latitude' => "90.4585",
                'longitude' => "90.4585",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::BAKERY->value,
                'name' => 'Sweet Treats Bakery',
                'slug' => Str::slug('Sweet Treats Bakery'),
                'phone' => '1234567892',
                'email' => 'sweettreats@example.com',
                'logo' => '12',
                'banner' => '13',
                'address' => '789 Sugar Road, City',
                'tax' => 5,
                'tax_number' => 'VAT123458',
                'is_featured' => true,
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 8.00,
                'delivery_charge' => 4.00,
                'delivery_time' => '20-40 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 20,
                'veg_status' => 0,
                'off_day' => 'Monday',
                'enable_saling' => 1,
                'meta_title' => 'Sweet Treats Bakery - Fresh Baked Goods',
                'meta_description' => 'Delicious cakes, pastries, and more at Sweet Treats Bakery.',
                'meta_image' => 'sweet_treats_meta_image.png',
                'latitude' => "90.4586",
                'longitude' => "90.4586",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::MEDICINE->value,
                'name' => 'Health First Pharmacy',
                'slug' => Str::slug('Health First Pharmacy'),
                'phone' => '1234567893',
                'email' => 'healthfirst@example.com',
                'logo' => '14',
                'banner' => '15',
                'address' => '101 Wellness Drive, City',
                'tax' => 5,
                'tax_number' => 'VAT123459',
                'is_featured' => true,
                'opening_time' => '09:00:00',
                'closing_time' => '22:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 10.00,
                'delivery_charge' => 5.00,
                'delivery_time' => '30-60 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 50,
                'veg_status' => 0,
                'off_day' => 'Sunday',
                'enable_saling' => 1,
                'meta_title' => 'Health First Pharmacy - Trusted Medicine Store',
                'meta_description' => 'Get all your prescription and health needs at Health First Pharmacy.',
                'meta_image' => 'health_first_meta_image.png',
                'latitude' => "90.4587",
                'longitude' => "90.4587",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::MAKEUP->value,
                'name' => 'Glamour Beauty',
                'slug' => Str::slug('Glamour Beauty'),
                'phone' => '1234567894',
                'email' => 'glamourbeauty@example.com',
                'logo' => '16',
                'banner' => '17',
                'address' => '202 Beauty Lane, City',
                'tax' => 5,
                'tax_number' => 'VAT123460',
                'is_featured' => true,
                'opening_time' => '10:00:00',
                'closing_time' => '20:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 12.00,
                'delivery_charge' => 4.00,
                'delivery_time' => '30-45 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 20,
                'veg_status' => 0,
                'off_day' => 'Tuesday',
                'enable_saling' => 1,
                'meta_title' => 'Glamour Beauty - Premium Makeup Store',
                'meta_description' => 'Shop the best in makeup and beauty products at Glamour Beauty.',
                'meta_image' => 'glamour_beauty_meta_image.png',
                'latitude' => "90.4588",
                'longitude' => "90.4588",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::BAGS->value,
                'name' => 'Bag World',
                'slug' => Str::slug('Bag World'),
                'phone' => '1234567895',
                'email' => 'bagworld@example.com',
                'logo' => '18',
                'banner' => '19',
                'address' => '303 Fashion Street, City',
                'tax' => 5,
                'tax_number' => 'VAT123461',
                'is_featured' => true,
                'opening_time' => '10:00:00',
                'closing_time' => '19:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 10.00,
                'delivery_charge' => 4.00,
                'delivery_time' => '20-30 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 30,
                'veg_status' => 0,
                'off_day' => 'Monday',
                'enable_saling' => 1,
                'meta_title' => 'Bag World - Your Destination for Stylish Bags',
                'meta_description' => 'Discover a wide range of fashionable bags at Bag World.',
                'meta_image' => 'bag_world_meta_image.png',
                'latitude' => "90.4589",
                'longitude' => "90.4589",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::CLOTHING->value,
                'name' => 'Trendy Apparel',
                'slug' => Str::slug('Trendy Apparel'),
                'phone' => '1234567896',
                'email' => 'trendyapparel@example.com',
                'logo' => '20',
                'banner' => '21',
                'address' => '404 Fashion Avenue, City',
                'tax' => 5,
                'tax_number' => 'VAT123462',
                'is_featured' => true,
                'opening_time' => '09:00:00',
                'closing_time' => '21:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 9.00,
                'delivery_charge' => 5.00,
                'delivery_time' => '30-50 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 40,
                'veg_status' => 0,
                'off_day' => 'Thursday',
                'enable_saling' => 1,
                'meta_title' => 'Trendy Apparel - Fashion for Everyone',
                'meta_description' => 'Shop trendy clothing for men, women, and kids at Trendy Apparel.',
                'meta_image' => 'trendy_apparel_meta_image.png',
                'latitude' => "90.4590",
                'longitude' => "90.4590",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::FURNITURE->value,
                'name' => 'Comfort Living Furniture',
                'slug' => Str::slug('Comfort Living Furniture'),
                'phone' => '1234567897',
                'email' => 'comfortliving@example.com',
                'logo' => '22',
                'banner' => '23',
                'address' => '505 Home Street, City',
                'tax' => 5,
                'tax_number' => 'VAT123463',
                'is_featured' => true,
                'opening_time' => '10:00:00',
                'closing_time' => '20:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 15.00,
                'delivery_charge' => 10.00,
                'delivery_time' => '1-2 hours',
                'delivery_self_system' => true,
                'delivery_take_away' => false,
                'order_minimum' => 100,
                'veg_status' => 0,
                'off_day' => 'Sunday',
                'enable_saling' => 1,
                'meta_title' => 'Comfort Living Furniture - Quality Furniture for Every Home',
                'meta_description' => 'Explore a wide range of furniture for your home at Comfort Living Furniture.',
                'meta_image' => 'comfort_living_meta_image.png',
                'latitude' => "90.4591",
                'longitude' => "90.4591",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::BOOKS->value,
                'name' => 'Readers Paradise',
                'slug' => Str::slug('Readers Paradise'),
                'phone' => '1234567898',
                'email' => 'readersparadise@example.com',
                'logo' => 'readers_paradise_logo.png',
                'banner' => 'readers_paradise_banner.png',
                'address' => '606 Knowledge Lane, City',
                'tax' => 5,
                'tax_number' => 'VAT123464',
                'is_featured' => true,
                'opening_time' => '09:00:00',
                'closing_time' => '18:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 12.00,
                'delivery_charge' => 4.00,
                'delivery_time' => '30-60 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 15,
                'veg_status' => 0,
                'off_day' => 'Saturday',
                'enable_saling' => 1,
                'meta_title' => 'Readers Paradise - Your Book Haven',
                'meta_description' => 'Find the best selection of books, from bestsellers to classics at Readers Paradise.',
                'meta_image' => 'readers_paradise_meta_image.png',
                'latitude' => "90.4592",
                'longitude' => "90.4592",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::GADGET->value,
                'name' => 'Tech Haven',
                'slug' => Str::slug('Tech Haven'),
                'phone' => '1234567899',
                'email' => 'techhaven@example.com',
                'logo' => 'tech_haven_logo.png',
                'banner' => 'tech_haven_banner.png',
                'address' => '707 Gadget Boulevard, City',
                'tax' => 5,
                'tax_number' => 'VAT123465',
                'is_featured' => true,
                'opening_time' => '10:00:00',
                'closing_time' => '21:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 10.00,
                'delivery_charge' => 5.00,
                'delivery_time' => '30-60 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 50,
                'veg_status' => 0,
                'off_day' => 'Friday',
                'enable_saling' => 1,
                'meta_title' => 'Tech Haven - Latest Gadgets & Electronics',
                'meta_description' => 'Shop the latest gadgets, electronics, and accessories at Tech Haven.',
                'meta_image' => 'tech_haven_meta_image.png',
                'latitude' => "90.4593",
                'longitude' => "90.4593",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::ANIMALS_PET->value,
                'name' => 'Paws & Claws',
                'slug' => Str::slug('Paws & Claws'),
                'phone' => '1234567901',
                'email' => 'pawsandclaws@example.com',
                'logo' => 'paws_and_claws_logo.png',
                'banner' => 'paws_and_claws_banner.png',
                'address' => '909 Pet Haven, City',
                'tax' => 5,
                'tax_number' => 'VAT123467',
                'is_featured' => true,
                'opening_time' => '09:00:00',
                'closing_time' => '20:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 8.00,
                'delivery_charge' => 7.00,
                'delivery_time' => '30-60 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 25,
                'veg_status' => 0,
                'off_day' => 'Thursday',
                'enable_saling' => 1,
                'meta_title' => 'Paws & Claws - Everything for Your Pets',
                'meta_description' => 'Get pet food, accessories, and more at Paws & Claws.',
                'meta_image' => 'paws_and_claws_meta_image.png',
                'latitude' => "90.4595",
                'longitude' => "90.4595",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'area_id' => 1,
                'store_seller_id' => 1,
                'store_type' => ProductType::FISH->value,
                'name' => 'The Fish Bowl',
                'slug' => Str::slug('The Fish Bowl'),
                'phone' => '1234567902',
                'email' => 'thefishbowl@example.com',
                'logo' => 'the_fish_bowl_logo.png',
                'banner' => 'the_fish_bowl_banner.png',
                'address' => '1010 Aquarium Street, City',
                'tax' => 5,
                'tax_number' => 'VAT123468',
                'is_featured' => true,
                'opening_time' => '10:00:00',
                'closing_time' => '19:00:00',
                'subscription_type' => 'commission',
                'admin_commission_type' => 'percent',
                'admin_commission_amount' => 10.00,
                'delivery_charge' => 5.00,
                'delivery_time' => '30-45 minutes',
                'delivery_self_system' => true,
                'delivery_take_away' => true,
                'order_minimum' => 20,
                'veg_status' => 0,
                'off_day' => 'Wednesday',
                'enable_saling' => 1,
                'meta_title' => 'The Fish Bowl - Fish & Aquatic Supplies',
                'meta_description' => 'Shop for fish, tanks, and aquarium supplies at The Fish Bowl.',
                'meta_image' => 'the_fish_bowl_meta_image.png',
                'latitude' => "90.4596",
                'longitude' => "90.4596",
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

    }
}
