<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('menus')->truncate();

        DB::table('menus')->insert([
            [
                'id' => 1,
                'name' => 'About',
                'url' => 'about-us',
                'icon' => 'fa fa-phone',
                'position' => 2,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-03-19 21:20:57',
                'updated_at' => '2025-04-07 02:42:03',
            ],[
                'id' => 2,
                'name' => 'Coupon',
                'url' => 'coupon',
                'icon' => 'fa fa-phone',
                'position' => 12,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-03-19 21:20:57',
                'updated_at' => '2025-04-07 02:42:03',
            ],
            [
                'id' => 3,
                'name' => 'Product',
                'url' => 'product',
                'icon' => null,
                'position' => 3,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:36:45',
                'updated_at' => '2025-04-08 06:30:36',
            ],
            [
                'id' => 4,
                'name' => 'Become A Seller',
                'url' => 'become-a-seller',
                'icon' => null,
                'position' => 4,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:37:33',
                'updated_at' => '2025-04-08 06:30:29',
            ],
            [
                'id' => 5,
                'name' => 'Pages',
                'url' => null,
                'icon' => null,
                'position' => 5,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:38:24',
                'updated_at' => '2025-04-08 06:29:09',
            ],
            [
                'id' => 6,
                'name' => 'Blog',
                'url' => 'blogs',
                'icon' => null,
                'position' => 6,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:39:02',
                'updated_at' => '2025-04-08 06:30:12',
            ],
            [
                'id' => 7,
                'name' => 'Privacy & Policy',
                'url' => 'privacy-policy',
                'icon' => null,
                'position' => 0,
                'parent_id' => 4,
                'parent_path' => '4',
                'menu_level' => 1,
                'menu_path' => 'Pages',
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:39:36',
                'updated_at' => '2025-04-08 06:29:58',
            ],
            [
                'id' => 8,
                'name' => 'Terms and conditions',
                'url' => 'terms-conditions',
                'icon' => null,
                'position' => 0,
                'parent_id' => 4,
                'parent_path' => '4',
                'menu_level' => 1,
                'menu_path' => 'Pages',
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:40:19',
                'updated_at' => '2025-04-08 06:29:49',
            ],
            [
                'id' => 9,
                'name' => 'Faq',
                'url' => null,
                'icon' => null,
                'position' => 0,
                'parent_id' => 4,
                'parent_path' => '4',
                'menu_level' => 1,
                'menu_path' => 'Pages',
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:40:50',
                'updated_at' => '2025-04-08 06:29:31',
            ],
            [
                'id' => 10,
                'name' => 'Contact',
                'url' => 'contact-us',
                'icon' => null,
                'position' => 7,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:41:11',
                'updated_at' => '2025-04-08 06:28:21',
            ],
            [
                'id' => 11,
                'name' => 'Home',
                'url' => '/',
                'icon' => null,
                'position' => 1,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:50:01',
                'updated_at' => '2025-04-08 06:31:03',
            ],
            [
                'id' => 12,
                'name' => 'Store',
                'url' => 'store/list',
                'icon' => null,
                'position' => 8,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:50:01',
                'updated_at' => '2025-04-08 06:31:03',
            ],
            [
                'id' => 13,
                'name' => 'Categories',
                'url' => 'product-category/list',
                'icon' => null,
                'position' => 9,
                'parent_id' => null,
                'parent_path' => null,
                'menu_level' => 0,
                'menu_path' => null,
                'is_visible' => true,
                'status' => 0,
                'created_at' => '2025-04-07 02:50:01',
                'updated_at' => '2025-04-08 06:31:03',
            ],
        ]);
    }
}
